[
  {
    productID: "001",
    title: "Men's Cotton T-Shirt",
    description: "Classic men's cotton t-shirt for casual wear.",
    price: 19.99,
    category: "Clothing",
    subcategory: "T-Shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    ratings: 4.5,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "002",
    title: "Women's Skinny Jeans",
    description: "Stylish skinny jeans for women.",
    price: 29.99,
    category: "Clothing",
    subcategory: "Jeans",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Black", "White"],
    ratings: 4.2,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "003",
    title: "Unisex Sports Shoes",
    description: "Comfortable sports shoes suitable for both men and women.",
    price: 39.99,
    category: "Shoes",
    subcategory: "Sports Shoes",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Black/White", "Blue/Gray", "Red/Black"],
    ratings: 4.7,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "004",
    title: "Men's Formal Shirt",
    description: "Elegant formal shirt for men, suitable for office wear.",
    price: 39.99,
    category: "Clothing",
    subcategory: "Shirts",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["White", "Light Blue", "Gray"],
    ratings: 4.6,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "005",
    title: "Women's Casual Dress",
    description: "Comfortable and stylish casual dress for women.",
    price: 49.99,
    category: "Clothing",
    subcategory: "Dresses",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Red", "Navy Blue"],
    ratings: 4.4,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "006",
    title: "Men's Cargo Shorts",
    description:
      "Durable and practical cargo shorts for men, ideal for outdoor activities.",
    price: 29.99,
    category: "Clothing",
    subcategory: "Shorts",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Khaki", "Green", "Brown"],
    ratings: 4.3,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "007",
    title: "Women's Running Shoes",
    description:
      "Lightweight and breathable running shoes for women, perfect for jogging and workouts.",
    price: 59.99,
    category: "Footwear",
    subcategory: "Shoes",
    sizes: ["US 6", "US 7", "US 8", "US 9", "US 10"],
    colors: ["Black/Pink", "White/Gray", "Blue/Orange"],
    ratings: 4.7,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "008",
    title: "Men's Hooded Sweatshirt",
    description:
      "Warm and cozy hooded sweatshirt for men, suitable for casual outings or lounging at home.",
    price: 34.99,
    category: "Clothing",
    subcategory: "Sweatshirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Navy Blue"],
    ratings: 4.5,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "009",
    title: "Women's Denim Jeans",
    description:
      "Classic denim jeans for women, featuring a slim fit and comfortable stretch fabric.",
    price: 44.99,
    category: "Clothing",
    subcategory: "Jeans",
    sizes: ["25", "26", "27", "28", "29", "30"],
    colors: ["Blue", "Black", "Gray"],
    ratings: 4.6,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "010",
    title: "Men's Casual Shirt",
    description:
      "Versatile and stylish casual shirt for men, suitable for various occasions.",
    price: 29.99,
    category: "Clothing",
    subcategory: "Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Blue", "Gray"],
    ratings: 4.4,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "011",
    title: "Women's Yoga Leggings",
    description:
      "High-waisted yoga leggings for women, crafted from breathable and moisture-wicking fabric.",
    price: 24.99,
    category: "Athletic Wear",
    subcategory: "Leggings",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Purple", "Teal"],
    ratings: 4.8,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
  {
    productID: "012",
    title: "Men's Leather Wallet",
    description:
      "Classic leather wallet for men, featuring multiple card slots and a bill compartment.",
    price: 39.99,
    category: "Accessories",
    subcategory: "Wallets",
    sizes: [],
    colors: ["Brown", "Black", "Tan"],
    ratings: 4.6,
    createdAt: "Current Timestamp",
    updatedAt: "Current Timestamp",
    deletedAt: null,
  },
];
