CREATE TABLE IF NOT EXISTS ecommerce.wishlists (
    wishlistID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productID INT NOT NULL,
    userID VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (productID) REFERENCES products(productID) ON DELETE CASCADE,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE,
    CONSTRAINT fk_wishlists_users FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
) DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;
