CREATE TABLE IF NOT EXISTS wishlists (
    wishlistID VARCHAR(255) NOT NULL PRIMARY KEY,
    productID VARCHAR(255) NOT NULL,
    userID VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (productID) REFERENCES products(productID) ON DELETE CASCADE,
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);